// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenImage(arg1:number,arg2:number,arg3:number,arg4:number):Promise<string>;

export function OpenSaveDialog():Promise<string>;

export function SaveB64Image(arg1:string,arg2:string):Promise<void>;
