// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenImage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenImage'](arg1, arg2, arg3, arg4);
}

export function OpenSaveDialog() {
  return window['go']['main']['App']['OpenSaveDialog']();
}

export function SaveB64Image(arg1, arg2) {
  return window['go']['main']['App']['SaveB64Image'](arg1, arg2);
}
